### ISSUE TITLE
IOError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by Alf71** [jladcr/Moses-for-Mere-Mortals#3]
Hi,

I followed the instructions to download the moses2tmx add-in.
When trying to convert the moses files into TMX I receive this error message:

IOError: [Errno 13] Permission denied: u'C:\\folder\\newfolder'

What would you recommend in this case?

Thanks in advance.

**Comment by jladcr** [comment]
Hi Alf71,

This program exists for already quite some years and we had never a report of such an error. Therefore, it seems acceptable to assume, though not absolutely sure, that your problem is local. Could you have still open the file in which the program wants to write? Do you have the correct permissions on that folder (if you do not have admin rights, a situation that is typical if you are using it in your work environment, you might not have them)? I'm afraid I can't do much more to try to help you.

João

**Comment by Alf71** [comment]
Olá,

Obrigado pela resposta.
Eu no entretanto descobri que basta mudar a extensao do ficheiro MOSES para TXT e
importá-lo em XLS para o poder editar.

E sim, em resposta às suas questoes, eu instalei a versao do Linux no VMware
e a versao do Moses2TMX em Windows. Depois de ter instalado todos os requisitos
acabei por encontrar sempre algo de errado no ficheiro log.

Mas pronto, o meu interesse estaria agora voltado para o ficheiro de 621 GB
que consegui baixar em

http://www.ir-facility.org/prototypes/marec 

mas nao descompactar bem no Windows. Assumo que tenha de ser aberto
em Linux...   : )


Mit freundlichen Grüßen / Best regards / Com os melhores cumprimentos





Alexandre






 


De Sena Viegas, MCIL, DipTransIoLET EN-PT, Freelance Translator 


TRANSLATION, PROOFREADING AND LOCALIZATION SERVICES


[EN-PT-(EN), DE-PT-(DE), (EN)-(DE)-(EN)]


  


Skype: TRADUTEMPO| Mobile: 0049 (0)172 662 9049 | Tel.: 0049 (0) 69 40952964 


  http://tradutempo.de | http://desenaviegas.com | 
http://vstmuseum.com



_____________________________________________________________________________________


                Von dem Präsidenten des Oberlandesgerichts Koblenz allgemein beeidigter
Dolmetscher
                der portugiesischen und ermächtigter Übersetzer der englischen und
portugiesischen 
                Sprache für gerichtliche und notarielle Angelegenheiten in
Rheinland-Pfalz
_____________________________________________________________________________________







Date: Thu, 17 Mar 2016 10:02:59 -0700

**Comment by jladcr** [comment]
Interessantes aventuras ;-)
